// import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import Slider from './components/Slider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>PrayerZon</title>
        <link rel="shortcut icon" href="assets/css/favicon.png" type="image/x-icon" />
        <link rel="stylesheet" href="assets/css/animate.css" />
        <link rel="stylesheet" href="assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="assets/css/all.min.css" />
        <link rel="stylesheet" href="assets/css/swiper.min.css" />
        <link rel="stylesheet" href="assets/css/lightcase.css" />
        {/* main css for template */}
        <link rel="stylesheet" href="assets/css/style.css" />
      </>

        <Header/>
        <Slider/>
        {children}

        <script src="assets/js/jquery-3.6.0.min.js"></script>
        <script src="assets/js/bootstrap.bundle.min.js"></script>
        <script src="assets/js/waypoints.min.js"></script>
        {/* <Script src="assets/js/all.min.js"></Script> */}
        <script src="assets/js/swiper.min.js"></script>
        <script src="assets/js/lightcase.js"></script>
        <script src="assets/js/isotope.pkgd.min.js"></script>
        <script src="assets/js/donate-range.js"></script>
        <script src="assets/js/jquery.counterup.min.js"></script>
        <script src="assets/js/wow.js"></script>
        <script src="assets/js/custom.js"></script>
        </body>
    </html>
  )
}
